Add SlogLoggerAdapter
ThreeDotsLabs/watermill pull request #355
Opened 2023-03-13 15:07 UTC by dkotik

Standard library is going to merge an experimental structured logging package `slog` soon. Therefore, it is important to support it.

Happy to have this parked until /exp/slog is merged into standard library. I am using the adapter in production already.

2023-08-29 14:50 UTC, GreyXor commented
Thanks @dkotik , works fine for me.
We can change the import to `import "log/slog"` now that slog is integrated into go 1.21

2023-08-29 17:46 UTC, dkotik commented
@GreyXor ok bumped the version up and switched over to `log/slog`. I propose that slog should be the default in place of regular log.

2023-09-01 12:04 UTC, GreyXor commented
> @GreyXor ok bumped the version up and switched over to `log/slog`. I propose that slog should be the default in place of regular log.

@dkotik thanks

2023-09-18 05:46 UTC, GreyXor commented
@dkotik gentle ping 🏓

2023-09-18 07:40 UTC, dkotik commented
> @dkotik gentle ping 🏓

Dear friend, I am not a maintainer here. I don't have the merge powers. What do I need to do?

2023-09-18 17:43 UTC, GreyXor commented
> > @dkotik gentle ping 🏓
> 
> Dear friend, I am not a maintainer here. I don't have the merge powers. What do I need to do?

@dkotik Greetings! I'm not requesting a merge at this time; rather, I'm reaching out for a code review. As you can observe, I've provided four suggestions for enhancing your code. Could you please take a moment to review them?

2023-09-19 11:57 UTC, dkotik commented
> > > @dkotik gentle ping 🏓
> > 
> > 
> > Dear friend, I am not a maintainer here. I don't have the merge powers. What do I need to do?
> 
> @dkotik Greetings! I'm not requesting a merge at this time; rather, I'm reaching out for a code review. As you can observe, I've provided four suggestions for enhancing your code. Could you please take a moment to review them?

I am confused. I am a Github newb, or there are something with permissions - I do not see any review comments in the code itself or in the list of "Reviewers" to the top right of this"

2023-09-19 13:06 UTC, GreyXor requested changes

2023-09-19 13:11 UTC, GreyXor commented
Thanks for your input, now you should be able to see it.

2023-09-19 16:42 UTC, dkotik commented on slog.go
> +func slogAttrsFromFields(fields LogFields) (result []any) {
Ok, also multiplying that by 2, since key and value both take a lot in that slice.

2023-09-19 16:47 UTC, dkotik commented on slog.go
> +		nil, // void context, following slog example
This is the only suggestion I would like to push back on. `context.TODO` suggests a future placement of context. There will never be one. I am extending my comment next to `nil` to explain why `nil` is here and also in the slog package itself:

> // Void context, following the slog example
// as it treats context slighly differently from
// normal usage, minding contextual
// values, but ignoring contextual deadline.
// See the [slog] package documentation
// for more details.

2023-09-19 18:50 UTC, GreyXor approved these changes

2023-09-19 18:51 UTC, GreyXor commented
Very good thanks!
LGTM

2023-09-19 18:54 UTC, GreyXor commented
LGTM, very good thanks!
@m110 can we consider a merge?

2023-09-24 09:50 UTC, m110 commented
@dkotik can you run `go mod tidy` on the repository, please? :)

2023-09-24 09:51 UTC, m110 commented on slog.go
> +const LevelTrace = slog.LevelDebug - 4
Can this be made unexported? 🤔 This lives in the top-level watermill package, so it would be best to keep unnecessary symbols out of it.

2023-09-24 09:52 UTC, m110 commented on slog.go
> +		// result = append(result, slog.Any(key, value))
Can we now drop the comment?

2023-09-24 09:53 UTC, m110 commented on slog.go
> +const LevelTrace = slog.LevelDebug - 4
Oh, looking at the test, I assume it might be useful for configuring Logger to follow the trace level 👍

2023-09-24 21:18 UTC, roblaszczak commented
Hey @dkotik, LGTM! Thanks for the contribution!

I'll address https://github.com/ThreeDotsLabs/watermill/pull/355#discussion_r1335154320 and fix CI on the `main` branch.

2023-09-24 21:19 UTC, merged